package com.loanx.customer.service.impl;

import com.loanx.customer.dto.request.CreateCustomerRequest;
import com.loanx.customer.dto.response.CustomerResponse;
import com.loanx.customer.entity.Customer;
import com.loanx.customer.exception.CustomerNotFoundException;
import com.loanx.customer.mapper.CustomerMapper;
import com.loanx.customer.repository.CustomerRepository;
import com.loanx.customer.service.CustomerService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

@Service
@RequiredArgsConstructor
@Transactional
public class CustomerServiceImpl implements CustomerService {

    private final CustomerRepository customerRepository;
    private final CustomerMapper customerMapper;

    @Override
    public CustomerResponse createCustomer(CreateCustomerRequest request) {

        Customer customer = customerMapper.toEntity(request);

        /*
         * Customer number is generated by Customer Service.
         * It is not accepted from the client.
         */
        customer.setCustomerNumber(generateCustomerNumber());

        Customer savedCustomer = customerRepository.save(customer);

        return customerMapper.toResponse(savedCustomer);
    }

    @Override
    @Transactional(readOnly = true)
    public CustomerResponse getCustomerById(UUID customerId) {

        Customer customer = customerRepository.findById(customerId)
                .orElseThrow(() -> new CustomerNotFoundException(customerId));

        return customerMapper.toResponse(customer);
    }

    @Override
    @Transactional(readOnly = true)
    public CustomerResponse getCustomerByNumber(String customerNumber) {

        Customer customer = customerRepository
                .findByCustomerNumber(customerNumber)
                .orElseThrow(() ->
                        new CustomerNotFoundException(customerNumber));

        return customerMapper.toResponse(customer);
    }

    private String generateCustomerNumber() {

        /*
         * Example:
         * CUS-7F4A91B2
         */
        return "CUS-" +
                UUID.randomUUID()
                        .toString()
                        .replace("-", "")
                        .substring(0, 8)
                        .toUpperCase();
    }
}